let tasks = [
    {
        id: 1,
        name: 'person1',
        title: 'Optimize mobile web performance for checkout flow',
        tag: 'Billing',
        jiraId: 'NUC-345',
        status: 'todo',
        priority: 'high',
        avatar: 'https://i2-prod.mirror.co.uk/incoming/article5614456.ece/ALTERNATES/s1227b/PAY-Lee-Griggs.jpg',
    },
    {
        id: 2,
        name: 'person2',
        title: 'Implement onboarding flow for travel booking users',
        tag: 'Accounts',
        jiraId: 'NUC-346',
        status: 'todo',
        priority: 'medium',
        avatar: 'https://thumbs.dreamstime.com/b/square-portrait-1784254.jpg',
    },
    {
        id: 3,
        name: 'person1',
        title: 'Design multi-destination search interface for mobile',
        tag: 'Accounts',
        jiraId: 'NUC-347',
        status: 'todo',
        priority: 'high',
        avatar: 'https://i2-prod.mirror.co.uk/incoming/article5614456.ece/ALTERNATES/s1227b/PAY-Lee-Griggs.jpg',
    },
    {
        id: 4,
        name: 'person1',
        title: 'Integrate billing system with third-party APIs',
        tag: 'Forms',
        jiraId: 'NUC-348',
        status: 'todo',
        priority: 'high',
        avatar: 'https://i2-prod.mirror.co.uk/incoming/article5614456.ece/ALTERNATES/s1227b/PAY-Lee-Griggs.jpg',
    },
    {
        id: 5,
        name: 'person3',
        title: 'Enhance account linking for repeat travel users',
        tag: 'Accounts',
        jiraId: 'NUC-349',
        status: 'todo',
        priority: 'low',
        avatar: 'https://img.freepik.com/premium-photo/face-portrait-casual-middleaged-man-white-square-background-generative-ai_741672-1331.jpg?w=2000%27'
    },
    {
        id: 6,
        name: 'person2',
        title: 'Create dynamic forms for onboarding workflow',
        tag: 'Forms',
        jiraId: 'NUC-350',
        status: 'todo',
        priority: 'medium',
        avatar: 'https://thumbs.dreamstime.com/b/square-portrait-1784254.jpg',
    },
    {
        id: 7,
        name: 'person1',
        title: 'Refactor mobile UI components for faster rendering',
        tag: 'Billing',
        jiraId: 'NUC-351',
        status: 'inProgress',
        priority: 'high',
        avatar: 'https://i2-prod.mirror.co.uk/incoming/article5614456.ece/ALTERNATES/s1227b/PAY-Lee-Griggs.jpg',
    },
    {
        id: 8,
        name: 'person4',
        title: 'Fix validation issues in travel onboarding forms',
        tag: 'Forms',
        jiraId: 'NUC-352',
        status: 'inProgress',
        priority: 'medium',
        avatar: 'https://tse3.mm.bing.net/th/id/OIP.r4b0T2uRLrCNgHKZ7lXzjwHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
    },
    {
        id: 9,
        name: 'person2',
        title: 'Improve search accuracy for multi-city queries',
        tag: 'Accounts',
        jiraId: 'NUC-353',
        status: 'inProgress',
        priority: 'high',
        avatar: 'https://thumbs.dreamstime.com/b/square-portrait-1784254.jpg',
    },
    {
        id: 10,
        name: 'person3',
        title: 'Review feedback on onboarding experience',
        tag: 'Feedback',
        jiraId: 'NUC-354',
        status: 'inReview',
        priority: 'medium',
        avatar: 'https://img.freepik.com/premium-photo/face-portrait-casual-middleaged-man-white-square-background-generative-ai_741672-1331.jpg?w=2000%27'
    },
    {
        id: 11,
        name: 'person4',
        title: 'Test edge cases for search UI responsiveness',
        tag: 'Accounts',
        jiraId: 'NUC-355',
        status: 'inReview',
        priority: 'high',
        avatar: 'https://tse3.mm.bing.net/th/id/OIP.r4b0T2uRLrCNgHKZ7lXzjwHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
    },
    {
        id: 12,
        name: 'person3',
        title: 'Validate feedback module integration with backend',
        tag: 'Feedback',
        jiraId: 'NUC-356',
        status: 'inReview',
        priority: 'low',
        avatar: 'https://i2-prod.mirror.co.uk/incoming/article5614456.ece/ALTERNATES/s1227b/PAY-Lee-Griggs.jpg',
    },
    {
        id: 13,
        name: 'person4',
        title: 'Audit billing-related UI components for consistency',
        tag: 'Billing',
        jiraId: 'NUC-357',
        status: 'inReview',
        priority: 'medium',
        avatar: 'https://tse3.mm.bing.net/th/id/OIP.r4b0T2uRLrCNgHKZ7lXzjwHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
    },
    {
        id: 14,
        name: 'person1',
        title: 'Finalize and deploy onboarding feature to production',
        tag: 'Feedback',
        jiraId: 'NUC-358',
        status: 'done',
        priority: 'high',
        avatar: 'https://i2-prod.mirror.co.uk/incoming/article5614456.ece/ALTERNATES/s1227b/PAY-Lee-Griggs.jpg',
    },
];

//check if localstorage is exist 

function getDefaultData()
{
    localStorage.setItem('tasks',JSON.stringify(tasks))
    return tasks;
}
 
export { tasks ,getDefaultData};